### PR TITLE
Added yarn support and cleaned up HTML sign in page so that it routes properly and allows signup

### PR DESCRIPTION
**Pull request by tac-eillA**

### CODE REVIEW

**Comment by tac-eillA** [comment]
I don't want to keep merging my pull requests myself because I want someone else to look them over before they are merged and approve them.

**Review by th3n3wguy — CHANGES_REQUESTED** [review]
I would suggest removing the .DS_Store file and then editing the .gitignore to make sure that git will ignore all of those files, regardless of the directory, in the future.

**Comment by tac-eillA** [comment]
Okay fixed the issue with the stray .DS_Store files in the public directory. Make sure to remove them from your git cache just in case (find . -name .DS_Store -print0 | xargs -0 git rm --ignore-unmatch) if youre using bash in project root.

**Review by th3n3wguy — APPROVED** [review]
Looks awesome now.

**Pull request merged**
